### ISSUE TITLE
Add method to determine does file is pgzip or not

### ISSUE THREAD

**Issue by vtolstov** [klauspost/pgzip#2]
I'm use many compressors (zip, gzip, pgzip, bgzf) and need to understand what file underline i have.
For example if i download bzgf file i need to enter to some code path to able to seek inside file, in case of gzip/pgzip i need to switch to other things (like enable more cpus or not..).
Does it possible to add such method?

**Comment by klauspost** [comment]
Could you elaborate a little bit (maybe with an example) on what you would like? I am not quite sure I understand what you are looking for.

**Comment by vtolstov** [comment]
I need a function like IsPGZIP  for example and create pgzip reader only this is pgzip, if not and for example bzgf - switch to it reader....

**Comment by klauspost** [comment]
Well, the file is a gzip file, and there is no visible differnce between it and a gzip file. Also, you might as well use the standard gzip decoder, since pgzip doesn't speed up decoding.

gzip files start with the byte sequence {0x1f, 0x8b, 0x08}

Since bzgf is a gzip extension, it will also register as a gzip, but it seems like you can call the HasEOF() to check if is a bzgf.

Zip files start with {0x50, 0x4B }, so you can test for that.

**Comment by vtolstov** [comment]
2015-02-15 15:11 GMT+03:00 Klaus Post <notifications@github.com>:

> Well, the file is a gzip file, and there is no visible differnce between
> it and a gzip file. Also, you might as well use the standard gzip decoder,
> since pgzip doesn't speed up decoding.
>
> gzip files start with the byte sequence {0x1f, 0x8b, 0x08}
>
> Since bzgf is a gzip extension, it will also register as a gzip, but it
> seems like you can call the HasEOF() to check if is a bzgf.
>
> Zip files start with {0x50, 0x4B }, so you can test for that.
>

Oh, thanks! so pgzip speedup on compression and not decompression?
For all other suggestions big thanks!


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru
jabber: vase@selfip.ru

**Comment by klauspost** [comment]
Yes - there is no way to do decompression multithreaded and maintain the compression ratio because to decompress a byte you need to know the result of the previous byte.

bzgf inserts "restarts", where the decoder starts with a blank slate. That allows them to skip to such a marker and begin decompression there, but it hurts the compression about 5-10% depending on their block size. Basically bigger blocks means better compression but slower seeks and more "chunky" multithreaded decoding. This can also be compared to splitting your input up into many individual gzip files.

pgzip doesn't hurt compression, and the result is very close to a single-threaded compression, but it doesn't allow seeking or multithreaded decoding.
